name: Deploy


on:
  push:
    branches: [ "master" ]

  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build
      uses: quasar-cli/quasar-build-action@v1
      with:
        args: build -m spa

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/spa

    - name: Create or Update gh-pages branch
      uses: actions/create-or-update-branch@v1
      with:
        branch: gh-pages
        artifact_patterns: dist/*