name: Deploy

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          npm i
          npm i -g @quasar/cli

      - name: Build
        run:  quasar build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa
